name: Task
description: Template for creating a task
body:
  - type: textarea
    id: content
    attributes:
      label: Description
      description: Detailed description of the task so the team knows exactly what needs to be done.
      placeholder: "Describe here what needs to be done..."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Add links, screenshots, or technical details if necessary.
      placeholder: "Link to ..."